n_estimators: 15000
booster: gbtree
device: cuda
objective: binary:logistic
tree_method: approx
grow_policy: lossguide
sampling_method: gradient_based
eval_metric:
  - logloss
  - auc
  - error
early_stopping_rounds: 200
learning_rate: 0.05
gamma: 0.79012017
subsample: 0.9224245
colsample_bytree: 0.4166666666666667
max_depth: 5
min_child_weight: 7
monotone_constraints:
  receive_2h_ko: 0
  spread_time: 1
  home: 0
  half_seconds_remaining: 0
  game_seconds_remaining: 0
  diff_time_ratio: 1
  score_differential: 1
  down: -1
  ydstogo: -1
  yardline_100: -1
  posteam_timeouts_remaining: 1
  defteam_timeouts_remaining: -1